name: tangtao-restaurant-app
services:
  - name: tangtao-backend
    source_dir: /backend/core
    github:
      repo: CedDevKh/tangtao-restaurant-booking
      branch: main
    build_command: |
      cd .. && pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    run_command: gunicorn --worker-tmp-dir /dev/shm core.wsgi:application --bind 0.0.0.0:8080
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.ondigitalocean.app"
      - key: DATABASE_URL
        type: SECRET
      - key: SECRET_KEY
        type: SECRET
      - key: CORS_ALLOWED_ORIGINS
        value: ${tangtao-frontend.PUBLIC_URL}
      - key: DJANGO_LOG_LEVEL
        value: "INFO"
    health_check:
      http_path: /health/
    
  - name: tangtao-frontend
    source_dir: /frontend
    github:
      repo: CedDevKh/tangtao-restaurant-booking
      branch: main
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${tangtao-backend.PUBLIC_URL}
      - key: NODE_ENV
        value: production

databases:
  - name: tangtao-db
    engine: PG
    version: "15"
    size: basic-xs
    num_nodes: 1
