# Generated by Django 5.2.4 on 2025-07-06 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.IntegerField(default=50, help_text='Maximum number of guests'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, help_text='Main restaurant image', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured restaurants appear on homepage'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.IntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')], default=2),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(choices=[('italian', 'Italian'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('mexican', 'Mexican'), ('indian', 'Indian'), ('french', 'French'), ('american', 'American'), ('thai', 'Thai'), ('mediterranean', 'Mediterranean'), ('korean', 'Korean'), ('vietnamese', 'Vietnamese'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
