# Generated by Django 5.2.4 on 2025-07-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_restaurant_capacity_restaurant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='closing_time',
            field=models.CharField(blank=True, help_text='Closing time (any format)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_url',
            field=models.TextField(blank=True, help_text='Main restaurant image', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_time',
            field=models.CharField(blank=True, help_text='Opening time (any format)', max_length=64, null=True),
        ),
    ]
