# Generated by Django 5.2.4 on 2025-07-26 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_restaurant_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='marketplace.restaurant'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='marketplace.offer'),
        ),
    ]
