# Generated by Django 5.2.4 on 2025-07-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_booking_restaurant_alter_booking_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(choices=[('italian', 'Italian'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('mexican', 'Mexican'), ('indian', 'Indian'), ('french', 'French'), ('american', 'American'), ('thai', 'Thai'), ('mediterranean', 'Mediterranean'), ('korean', 'Korean'), ('vietnamese', 'Vietnamese'), ('khmer', 'Khmer'), ('fine_dining', 'Fine Dining'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
