# Generated by Django 5.2.4 on 2025-07-27 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_restaurant_cuisine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='days_of_week',
            field=models.CharField(blank=True, help_text="Days of week (0=Monday, 6=Sunday). E.g., '0,1,2,3,4' for weekdays", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 7, 27), help_text='End date for the offer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on featured offers'),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_people_per_booking',
            field=models.IntegerField(default=6, help_text='Maximum people per booking for this offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_advance_booking',
            field=models.IntegerField(default=1, help_text='Minimum hours in advance for booking'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount'), ('amount', 'Fixed Amount Discount'), ('special', 'Special Offer')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='recurring',
            field=models.CharField(choices=[('none', 'One-time offer'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 7, 27), help_text='Start date for the offer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='available_quantity',
            field=models.IntegerField(help_text='Number of bookings available for this offer per day'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_time',
            field=models.TimeField(help_text='Daily end time for the offer (e.g., 21:00 for 9 PM)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_time',
            field=models.TimeField(help_text='Daily start time for the offer (e.g., 18:00 for 6 PM)'),
        ),
    ]
