# Generated by Django 5.2.4 on 2025-08-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_booking_slot_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Start time for this half-hour slot (minutes must be 00 or 30)')),
                ('end_time', models.TimeField(help_text='End time for this half-hour slot (typically start+30m)')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='marketplace.offer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_time_slots', to='marketplace.restaurant')),
            ],
            options={
                'verbose_name': 'Offer Time Slot',
                'verbose_name_plural': 'Offer Time Slots',
                'ordering': ['start_time'],
                'unique_together': {('offer', 'start_time')},
            },
        ),
    ]
