# Generated by Django 5.2.4 on 2025-09-02 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_restaurant_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_id', models.CharField(max_length=40, unique=True)),
                ('party_size', models.PositiveIntegerField()),
                ('contact', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('confirmed', 'Confirmed'), ('expired', 'Expired')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='marketplace.bookingslot')),
            ],
            options={
                'verbose_name': 'Booking Hold',
                'verbose_name_plural': 'Booking Holds',
                'indexes': [models.Index(fields=['hold_id'], name='marketplace_hold_id_ae69ef_idx'), models.Index(fields=['status', 'expires_at'], name='marketplace_status_a015d8_idx')],
            },
        ),
    ]
