# Generated by Django 5.2.4 on 2025-09-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_alter_booking_diner_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/covers/'),
        ),
    ]
